name: Generate F-Droid repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
            11
            17
          distribution: 'temurin'
          architecture: x64

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: tools platform-tools

      - name: Restore correct mtime
        run: |
          sudo apt install git-restore-mtime 
          git restore-mtime

      - name: Install F-Droid server software
        run: |
         sudo add-apt-repository ppa:fdroid/fdroidserver
         sudo apt-get update
         sudo apt-get install fdroidserver

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml

      - uses: actions/setup-go@v2
        name: Set up Go
        with:
          go-version: '^1.17.0' 
      
      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: fdroid/index.html
          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
          favicon: '<link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon.png">'

      - name: Fix icons path
        run: sed -i 's/fdroid/repo/icons//repo/icons//g' fdroid/index.html

      - name: Copy qrcode.png to fdroid folder and fix qrcode path
        run: mkdir -p fdroid/.github; cp .github/qrcode.png fdroid/.github/qrcode.png

      - name: Remove saved secrets
        run: rm fdroid/keystore.p12; rm fdroid/config.yml
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fdroid
